version: "3.9"

services:
  family-tree:
    container_name: family-tree
    restart: always
    build:
      context: ./src
    working_dir: /usr/family-tree/src
    command: sh -c "
        alembic upgrade head &&
        python main.py
      "
    environment:
      - ENVIRONMENT=container
    env_file:
      - ./src/.env
    networks:
      - family-tree-network
    ports:
      - "8888:8888"
    depends_on:
      - family-tree-db
    healthcheck:
      test: curl -f http://localhost:8888/api/healthcheck
      interval: 60s
      timeout: 3s
      retries: 3

  family-tree-db:
    image: postgres:16
    container_name: family-tree-db
    restart: always
    command: -p 5832
    environment:
      - POSTGRES_USER=family-tree-db
      - POSTGRES_PASSWORD=family-tree-db
      - POSTGRES_DB=family-tree-db
    networks:
      - family-tree-network
    expose:
      - "5832"
    ports:
      - "5832:5832"
    volumes:
      - family-tree-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -p 5832 -U family-tree-map-db -d family-tree-map-db
      interval: 60s
      timeout: 3s
      retries: 3


volumes:
  family-tree-db-data:


networks:
  family-tree-network:
    name: family-tree-network
    external: true
